In [9]:
### import libraries
import earthpy ### manage local data
import holoviews as hv ### save interactive plots
import hvplot.pandas ### make interactive plots
import pandas as pd ### work with tabular data

### Loading and Saving Data
The code in the three cells below downloaded the data, read it into a dataframe, and saved it as a csv file. Now, that I have the csv file, I have commented out the following three cells, so I don't have to run the whole thing again, given that I can use the saved csv file for my analysis.

In [10]:
### make URL for data
ncei_url = ('https://www.ncei.noaa.gov/access/services/da'
            'ta/v1?dataset=daily-summaries&dataTypes=TAVG&stations'
            '=TI000038836&startDate=1980-01-01&endDate=2022-12-31&units=standard')

ncei_url

'https://www.ncei.noaa.gov/access/services/data/v1?dataset=daily-summaries&dataTypes=TAVG&stations=TI000038836&startDate=1980-01-01&endDate=2022-12-31&units=standard'

In [11]:
### get the data using URL
dushanbe_temp_df = pd.read_csv(
    ncei_url, 

    ### set the index column to DATE
    index_col = 'DATE',

    ### parse the index column as date-time
    parse_dates = True,

    ### set NA values to NaN
    na_values = ['NaN']
    )

dushanbe_temp_df

KeyboardInterrupt:

In [ ]:
### save the climate data
dushanbe_temp_df.to_csv('dushanbe_temp_data.csv')

In [ ]:
### get the data using URL
dushanbe_temp_df = pd.read_csv(
    'dushanbe_temp_data.csv', 
    
    ### set the index column to DATE
    index_col = 'DATE',

    ### parse the index column as date-time
    parse_dates = True,

    ### set NA values to NaN
    na_values = ['NaN']
    )

dushanbe_temp_df

                STATION  TAVG
DATE
1980-01-01  TI000038836  40.0
1980-01-02  TI000038836  40.0
1980-01-03  TI000038836  38.0
1980-01-04  TI000038836  39.0
1980-01-05  TI000038836  40.0
...                 ...   ...
2022-12-28  TI000038836  45.0
2022-12-29  TI000038836  40.0
2022-12-30  TI000038836  41.0
2022-12-31  TI000038836  35.0
2023-01-01  TI000038836  34.0

[14848 rows x 2 columns]

In [ ]:
### check that data was imported into a pandas DF
type(dushanbe_temp_df)

pandas.core.frame.DataFrame

In [ ]:
### create a dataframe with only the TAVG column
dushanbe_temp_df = dushanbe_temp_df[['TAVG']]

dushanbe_temp_df

            TAVG
DATE
1980-01-01  40.0
1980-01-02  40.0
1980-01-03  38.0
1980-01-04  39.0
1980-01-05  40.0
...          ...
2022-12-28  45.0
2022-12-29  40.0
2022-12-30  41.0
2022-12-31  35.0
2023-01-01  34.0

[14848 rows x 1 columns]

In [ ]:
### make a new DF with expressive column name
dushanbe_temp_units_df = dushanbe_temp_df.rename(columns={
    'TAVG': 'avg_temp_fahr',
})

dushanbe_temp_units_df

            avg_temp_fahr
DATE
1980-01-01           40.0
1980-01-02           40.0
1980-01-03           38.0
1980-01-04           39.0
1980-01-05           40.0
...                   ...
2022-12-28           45.0
2022-12-29           40.0
2022-12-30           41.0
2022-12-31           35.0
2023-01-01           34.0

[14848 rows x 1 columns]

In [ ]:
### convert units with a function
def fahr_to_cel(temperature):
    """Convert temperature to Celsius"""

    return (temperature - 32) * (5 / 9)

### use fnxn to add a celsius col
dushanbe_temp_units_df['avg_temp_cel'] = (
    dushanbe_temp_units_df['avg_temp_fahr']
    .apply(fahr_to_cel)
    )

dushanbe_temp_units_df

            avg_temp_fahr  avg_temp_cel
DATE
1980-01-01           40.0      4.444444
1980-01-02           40.0      4.444444
1980-01-03           38.0      3.333333
1980-01-04           39.0      3.888889
1980-01-05           40.0      4.444444
...                   ...           ...
2022-12-28           45.0      7.222222
2022-12-29           40.0      4.444444
2022-12-30           41.0      5.000000
2022-12-31           35.0      1.666667
2023-01-01           34.0      1.111111

[14848 rows x 2 columns]